import type { Case, Event, Course, AppRecommendation, User } from '@/types';

export const mockUser: User = {
  id: '1',
  feishu_open_id: 'ou_xxx',
  name: '张三',
  avatar: '',
  department: 'HRBP',
  roles: ['user'],
  bio: 'AI 爱好者',
  points: 120,
  level: 'AI探索者',
  created_at: '2026-05-01T00:00:00Z',
};

export const mockCases: Case[] = [
  {
    id: '1',
    title: '用 Claude 优化招聘 JD 撰写效率',
    summary: '通过 Prompt Engineering 让 AI 自动生成高质量招聘 JD，效率提升 3 倍',
    content: '<p>详细内容...</p>',
    cover_image: '',
    category: 'HSSC_招聘',
    ai_tools: ['Claude/Claude Code', 'ChatGPT/Codex'],
    author: { id: '1', name: '张三', avatar: '', department: 'HRBP' },
    status: 'published',
    view_count: 156,
    like_count: 32,
    bookmark_count: 18,
    comment_count: 5,
    event_id: null,
    attachments: [],
    created_at: '2026-05-15T10:00:00Z',
    updated_at: '2026-05-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'AI 辅助绩效评语生成实践',
    summary: '利用大模型批量生成绩效评语初稿，HR 只需微调即可',
    content: '<p>详细内容...</p>',
    cover_image: '',
    category: 'HCOE/HSSC_薪酬绩效',
    ai_tools: ['Qwen'],
    author: { id: '2', name: '李四', avatar: '', department: 'COE' },
    status: 'published',
    view_count: 89,
    like_count: 21,
    bookmark_count: 12,
    comment_count: 3,
    event_id: null,
    attachments: [],
    created_at: '2026-05-14T08:00:00Z',
    updated_at: '2026-05-14T08:00:00Z',
  },
  {
    id: '3',
    title: '用 AI 搭建员工培训知识库',
    summary: '基于 RAG 技术搭建 HR 内部知识问答系统',
    content: '<p>详细内容...</p>',
    cover_image: '',
    category: 'HCOE_培训',
    ai_tools: ['Claude/Claude Code'],
    author: { id: '3', name: '王五', avatar: '', department: 'HR' },
    status: 'published',
    view_count: 234,
    like_count: 45,
    bookmark_count: 30,
    comment_count: 8,
    event_id: '1',
    attachments: [],
    created_at: '2026-05-13T14:00:00Z',
    updated_at: '2026-05-13T14:00:00Z',
  },
  {
    id: '4',
    title: 'AI 自动化面试排期系统',
    summary: '用 AI + 飞书日历自动协调面试官和候选人时间',
    content: '<p>详细内容...</p>',
    cover_image: '',
    category: 'HSSC_招聘',
    ai_tools: ['ChatGPT/Codex'],
    author: { id: '4', name: '赵六', avatar: '', department: 'HRBP' },
    status: 'published',
    view_count: 178,
    like_count: 38,
    bookmark_count: 22,
    comment_count: 6,
    event_id: null,
    attachments: [],
    created_at: '2026-05-12T09:00:00Z',
    updated_at: '2026-05-12T09:00:00Z',
  },
  {
    id: '5',
    title: '用 AI 生成薪酬分析报告',
    summary: '让 AI 自动分析薪酬数据并生成可视化报告',
    content: '<p>详细内容...</p>',
    cover_image: '',
    category: 'HCOE/HSSC_薪酬绩效',
    ai_tools: ['Claude/Claude Code'],
    author: { id: '5', name: '钱七', avatar: '', department: 'COE' },
    status: 'published',
    view_count: 145,
    like_count: 29,
    bookmark_count: 16,
    comment_count: 4,
    event_id: null,
    attachments: [],
    created_at: '2026-05-11T16:00:00Z',
    updated_at: '2026-05-11T16:00:00Z',
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'HRAS AI 大赛 · 第一赛季',
    description: '用 AI 解决 HR 实际工作场景中的问题，展示你的 AI 实践能力！',
    cover_image: '',
    rules: '1. 参赛者需为 HR 体系员工\n2. 提交一个 AI 应用案例\n3. 评审维度：创新性、实用性、可复制性',
    prizes: '一等奖：5000元 + 荣誉证书\n二等奖：3000元 + 荣誉证书\n三等奖：1000元 + 荣誉证书',
    start_time: '2026-05-01T00:00:00Z',
    end_time: '2026-06-30T23:59:59Z',
    registration_deadline: '2026-06-15T23:59:59Z',
    status: 'ongoing',
    registration_count: 45,
    max_participants: 100,
    created_at: '2026-04-25T00:00:00Z',
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'AI 工具入门：从零开始认识大模型',
    description: '适合 AI 小白的基础课程，了解什么是大模型、如何使用 AI 工具',
    cover_image: '',
    instructor: 'AI 培训组',
    difficulty: '初阶',
    duration: '2小时',
    content_type: 'video',
    courseware_url: '',
    video_url: '',
    chapters: [
      { id: '1', title: '什么是大模型？', content_url: '', content: '', duration: '30分钟', sort_order: 1 },
      { id: '2', title: '常用 AI 工具介绍', content_url: '', content: '', duration: '30分钟', sort_order: 2 },
      { id: '3', title: 'Prompt 基础技巧', content_url: '', content: '', duration: '30分钟', sort_order: 3 },
      { id: '4', title: '实操练习', content_url: '', content: '', duration: '30分钟', sort_order: 4 },
    ],
    student_count: 89,
    rating: 4.8,
    like_count: 12,
    bookmark_count: 5,
    comment_count: 3,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'HR 场景 AI 实操：招聘篇',
    description: '手把手教你用 AI 优化招聘全流程',
    cover_image: '',
    instructor: '张三',
    difficulty: '进阶',
    duration: '3小时',
    content_type: 'doc',
    courseware_url: '',
    video_url: '',
    chapters: [
      { id: '1', title: 'AI 生成 JD', content_url: '', content: '', duration: '45分钟', sort_order: 1 },
      { id: '2', title: 'AI 筛选简历', content_url: '', content: '', duration: '45分钟', sort_order: 2 },
      { id: '3', title: 'AI 面试问题生成', content_url: '', content: '', duration: '45分钟', sort_order: 3 },
      { id: '4', title: 'AI 面试评估', content_url: '', content: '', duration: '45分钟', sort_order: 4 },
    ],
    student_count: 56,
    rating: 4.6,
    like_count: 8,
    bookmark_count: 3,
    comment_count: 1,
    created_at: '2026-04-15T00:00:00Z',
  },
  {
    id: '3',
    title: '高级 Prompt Engineering 技巧',
    description: '深入学习 Prompt 设计模式和高级技巧',
    cover_image: '',
    instructor: '李四',
    difficulty: '高阶',
    duration: '4小时',
    content_type: 'video',
    courseware_url: '',
    video_url: '',
    chapters: [
      { id: '1', title: 'Prompt 设计原则', content_url: '', content: '', duration: '60分钟', sort_order: 1 },
      { id: '2', title: 'Chain of Thought', content_url: '', content: '', duration: '60分钟', sort_order: 2 },
      { id: '3', title: 'Few-shot Learning', content_url: '', content: '', duration: '60分钟', sort_order: 3 },
      { id: '4', title: '实战案例', content_url: '', content: '', duration: '60分钟', sort_order: 4 },
    ],
    student_count: 34,
    rating: 4.9,
    like_count: 15,
    bookmark_count: 7,
    comment_count: 4,
    created_at: '2026-05-01T00:00:00Z',
  },
];

export const mockApps: AppRecommendation[] = [
  {
    id: '1',
    name: 'Claude',
    logo: '',
    description: 'Anthropic 出品的 AI 助手，擅长长文本理解和分析',
    content: '',
    resource_type: 'ai_tool',
    category: '对话类',
    scenarios: ['文档分析', '写作', '问答'],
    official_url: 'https://claude.ai',
    rating: 4.8,
    user_count: 120,
    like_count: 45,
    dislike_count: 2,
    status: 'published',
    author_id: null,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: '2',
    name: '通义千问',
    logo: '',
    description: '阿里巴巴出品的大语言模型，中文能力强',
    content: '',
    resource_type: 'ai_tool',
    category: '对话类',
    scenarios: ['中文写作', '数据分析', '代码生成'],
    official_url: 'https://tongyi.aliyun.com',
    rating: 4.5,
    user_count: 200,
    like_count: 67,
    dislike_count: 5,
    status: 'published',
    author_id: null,
    created_at: '2026-04-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Dify',
    logo: '',
    description: '开源 LLM 应用开发平台，支持 RAG 和工作流',
    content: '',
    resource_type: 'ai_tool',
    category: '自动化',
    scenarios: ['知识库搭建', 'AI 应用开发', '工作流自动化'],
    official_url: 'https://dify.ai',
    rating: 4.7,
    user_count: 80,
    like_count: 35,
    dislike_count: 1,
    status: 'published',
    author_id: null,
    created_at: '2026-05-01T00:00:00Z',
  },
];
