import type { Event, Course, AppRecommendation, User } from '@/types';

export const mockUser: User = {
  id: '1',
  feishu_open_id: 'ou_xxx',
  name: '张三',
  avatar: '',
  department: 'HRBP',
  roles: ['user'],
  bio: 'AI 爱好者',
  points: 120,
  level: 'AI探索者',
  created_at: '2026-05-01T00:00:00Z',
};

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'HRAS AI 大赛 · 第一赛季',
    description: '用 AI 解决 HR 实际工作场景中的问题，展示你的 AI 实践能力！',
    cover_image: '',
    rules: '1. 参赛者需为 HR 体系员工\n2. 提交一个 AI 应用案例\n3. 评审维度：创新性、实用性、可复制性',
    prizes: '一等奖：5000元 + 荣誉证书\n二等奖：3000元 + 荣誉证书\n三等奖：1000元 + 荣誉证书',
    start_time: '2026-05-01T00:00:00Z',
    end_time: '2026-06-30T23:59:59Z',
    registration_deadline: '2026-06-15T23:59:59Z',
    status: 'ongoing',
    registration_count: 45,
    max_participants: 100,
    created_at: '2026-04-25T00:00:00Z',
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'AI 工具入门：从零开始认识大模型',
    description: '适合 AI 小白的基础课程，了解什么是大模型、如何使用 AI 工具',
    cover_image: '',
    instructor: 'AI 培训组',
    difficulty: '初阶',
    duration: '2小时',
    content_type: 'video',
    courseware_url: '',
    video_url: '',
    chapters: [
      { id: '1', title: '什么是大模型？', content_url: '', content: '', duration: '30分钟', sort_order: 1 },
      { id: '2', title: '常用 AI 工具介绍', content_url: '', content: '', duration: '30分钟', sort_order: 2 },
      { id: '3', title: 'Prompt 基础技巧', content_url: '', content: '', duration: '30分钟', sort_order: 3 },
      { id: '4', title: '实操练习', content_url: '', content: '', duration: '30分钟', sort_order: 4 },
    ],
    student_count: 89,
    rating: 4.8,
    like_count: 12,
    bookmark_count: 5,
    comment_count: 3,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'HR 场景 AI 实操：招聘篇',
    description: '手把手教你用 AI 优化招聘全流程',
    cover_image: '',
    instructor: '张三',
    difficulty: '进阶',
    duration: '3小时',
    content_type: 'doc',
    courseware_url: '',
    video_url: '',
    chapters: [
      { id: '1', title: 'AI 生成 JD', content_url: '', content: '', duration: '45分钟', sort_order: 1 },
      { id: '2', title: 'AI 筛选简历', content_url: '', content: '', duration: '45分钟', sort_order: 2 },
      { id: '3', title: 'AI 面试问题生成', content_url: '', content: '', duration: '45分钟', sort_order: 3 },
      { id: '4', title: 'AI 面试评估', content_url: '', content: '', duration: '45分钟', sort_order: 4 },
    ],
    student_count: 56,
    rating: 4.6,
    like_count: 8,
    bookmark_count: 3,
    comment_count: 1,
    created_at: '2026-04-15T00:00:00Z',
  },
  {
    id: '3',
    title: '高级 Prompt Engineering 技巧',
    description: '深入学习 Prompt 设计模式和高级技巧',
    cover_image: '',
    instructor: '李四',
    difficulty: '高阶',
    duration: '4小时',
    content_type: 'video',
    courseware_url: '',
    video_url: '',
    chapters: [
      { id: '1', title: 'Prompt 设计原则', content_url: '', content: '', duration: '60分钟', sort_order: 1 },
      { id: '2', title: 'Chain of Thought', content_url: '', content: '', duration: '60分钟', sort_order: 2 },
      { id: '3', title: 'Few-shot Learning', content_url: '', content: '', duration: '60分钟', sort_order: 3 },
      { id: '4', title: '实战案例', content_url: '', content: '', duration: '60分钟', sort_order: 4 },
    ],
    student_count: 34,
    rating: 4.9,
    like_count: 15,
    bookmark_count: 7,
    comment_count: 4,
    created_at: '2026-05-01T00:00:00Z',
  },
];

export const mockApps: AppRecommendation[] = [
  {
    id: '1',
    name: 'Claude',
    logo: '',
    description: 'Anthropic 出品的 AI 助手，擅长长文本理解和分析',
    content: '',
    category: 'AI Agent/大模型',
    scenarios: ['文档分析', '写作', '问答'],
    official_url: 'https://claude.ai',
    rating: 4.8,
    user_count: 120,
    like_count: 45,
    dislike_count: 2,
    status: 'published',
    author_id: null,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: '2',
    name: '通义千问',
    logo: '',
    description: '阿里巴巴出品的大语言模型，中文能力强',
    content: '',
    category: 'AI Agent/大模型',
    scenarios: ['中文写作', '数据分析', '代码生成'],
    official_url: 'https://tongyi.aliyun.com',
    rating: 4.5,
    user_count: 200,
    like_count: 67,
    dislike_count: 5,
    status: 'published',
    author_id: null,
    created_at: '2026-04-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Dify',
    logo: '',
    description: '开源 LLM 应用开发平台，支持 RAG 和工作流',
    content: '',
    category: '好用 Skills',
    scenarios: ['知识库搭建', 'AI 应用开发', '工作流自动化'],
    official_url: 'https://dify.ai',
    rating: 4.7,
    user_count: 80,
    like_count: 35,
    dislike_count: 1,
    status: 'published',
    author_id: null,
    created_at: '2026-05-01T00:00:00Z',
  },
];
